### ISSUE TITLE
RFE: Interpolating on key level

### ISSUE THREAD

**Issue by thmo** [DiffSK/configobj#141] opened 2017-02-20 19:23 UTC
Given that ini file:
```
[DEFAULT]
foo = 42

[s]
bar = 43
baz = %(foo)s
```

ConfigParser is able to return a value for key `foo` in section `s`:
```
print c.get('s', 'bar')  # 43
print c.get('s', 'baz')  # 42
print c.get('s', 'foo')  # 42
```

Using `ConfigObj` however, a `KeyError` is thrown:
```
print c['s']['bar']  # 43
print c['s']['baz']  # 42
print c['s']['foo']  # KeyError 'foo'
```

`ConfigParser`'s behavior is quite handy in some situations, as it allows to 'inherit' keys from a default section.

Any chance this could be implemented?

**Comment by jhermann** [comment] 2017-02-21 10:13
Dupe of #101

**Closed by jhermann** 2017-02-21 10:13 UTC

**Comment by thmo** [comment] 2017-02-21 11:09
Sorry for the duplicate (although I think it is more a duplicate of #109).
